### ISSUE TITLE
Still experimental

### ISSUE THREAD

**Issue by AdrienPensart** [click-contrib/click-aliases#1]
is this still experimental ?

could it be uploaded on pypi ?

or is it superseded by https://github.com/pallets/click/blob/master/examples/aliases/aliases.py ?

**Comment by jayvdb** [comment]
@AdrienPensart , I believe this is still needed.  c.f. https://github.com/pallets/click/issues/1346

There is a derivative by @hotoffthehamster which is on PyPI https://pypi.org/project/click-alias/ , however the latest alpha release 0.1.1a3 uses a *custom* fork of click.

I believe the prior release is ok https://pypi.org/project/click-alias/0.1.1a2/ .  And the current codebase is ok with click 7, so this could be resolved, however I've pinged and email the author about https://github.com/hotoffthehamster/click-alias/pull/3 with no response.

It might be necessary to try merging the changes in that repo back here, and hope to get some traction here instead, and at least get a pre-release on PyPI.

https://pypistats.org/packages/click-alias shows it is in use, despite being experimental.  That is what pre-releases are for.

**Comment by jayvdb** [comment]
The only feature I could find in that fork was Click 7 support, which I've re-implemented at https://github.com/click-contrib/click-aliases/pull/3

**Comment by rbonthond** [comment]
I have no clue how to upload things to pypi, if someone wants to jump in, that's ok with me

**Comment by rbonthond** [comment]
I've merged all outstanding requests, removed the experimental line, and created https://pypi.org/project/click-aliases/.

**Comment by hotoffthehamster** [comment]
Hi, @jayvdb,

Thanks for reaching out about my fork of click-alias.

(And sorry for the delay, I was on an extended vacation!)

You are correct, you pulled everything from my fork that should be of interest.

FYI, I deleted the PyPI project, and freed up the ``click-alias`` name (I realize
you probably published to ``click-aliases`` because the former was taken!).

I also moved my fork to https://pypi.org/project/click-hotoffthehamster-alias/,
to indicate that it's based on a Click fork that I need to support a few features
I added for ``dob`` (https://pypi.org/project/dob), which is a Hamster time tracker
replacement.

Thanks for your work on this plugin! I appreciate being able to use it for my projects.

Sincerely,

Landon (for HotOffTheHamster)
